version: '3.4'

name: acmepowersolutions
services:
  meterdatamanagement.api:
    container_name: meterdatamanagement-api
    image: ${DOCKER_REGISTRY:-acmepowersolutions/}meterdatamanagement-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: MeterDataManagement/MeterDataManagement.Api/Dockerfile
    depends_on:
    - elasticsearch
    - meterdatamanagement.postgresql

  meterdatamanagement.meter:
    container_name: meterdatamanagement-meter
    image: ${DOCKER_REGISTRY:-acmepowersolutions/}meterdatamanagement-meter:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: MeterDataManagement/MeterDataManagement.Meter/Dockerfile
    depends_on:
    - elasticsearch

  meterdatamanagement.postgresql:
    container_name: meterdatamanagement-postgressql
    image: "ionx/postgres-plv8:12.2"
    ports: 
    - "5432:5432"
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: meterdatamanagement
        NAMEDATALEN: 100

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.3.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: kibana:8.3.2
    environment:
      - ELASTICSEARCH_HOSTS=http://host.docker.internal:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601