using ConsumptionNotificationSubscriptionService.Contracts.v1_0;

namespace ConsumptionSubscriptionService.Contracts.Commands.v1_0;

public record SubscribeToAbnormalConsumptionNotifications(int CustomerId, CommunicationChannel CommunicationChannel);
