using ConsumptionNotificationSubscriptionService.Contracts.v1_0;

namespace ConsumptionSubscriptionService.Contracts.Queries.v1_0;

public record GetAbnormalConsumptionSubscriptionResponse(int CustomerId, CommunicationChannel CommunicationChannel, DateTimeOffset CreatedOn);