using ConsumptionNotificationSubscriptionService.Contracts;

namespace ConsumptionSubscriptionService.Contracts.Commands;

public record SubscribeToAbnormalConsumptionNotifications(int CustomerId, CommunicationChannel CommunicationChannel);
