using ConsumptionNotificationSubscriptionService.Contracts;

namespace CustomerProfileService.Contracts.Queries;

public record GetNotificationSettingsResponse(int CustomerId, CommunicationChannel PreferedCommunicationChannel);